apiVersion: v1
kind: Service
metadata:
  name: tetris-service
  labels:
    app: tetris-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: tetris-app
